import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import useSocket from '@/hooks/init-socket'

const inter = Inter({ subsets: ['latin'] })

const Index = () => {
  const socket = useSocket()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <div className={styles.description}>
            <p>
              Get started by editing&nbsp;
              <code className={styles.code}>{socket.socketData}</code>
            </p>
          </div>
        </div>
      </main>
    </>
  )
}

export default Index
